<a href="https://colab.research.google.com/github/RifleB-1311/Baitap-numpy/blob/main/Numpy04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

Ghi chú: sau mỗi lần sinh ra giá trị cho vector, hãy cho biết số chiều của vector được sinh ra và
số chiều của vector chuyển vị của vector đó; cho biết kích thước của vector a và vector chuyển vị
của vector a.

In [1]:
import numpy as np
a = np.arange(-3, 4, 1, dtype=int)
a1 = np.transpose(a)
b = np.linspace(0, 6, 7)
b1 = np.transpose(b)
c = np.logspace(1.0, 7.0, num=7, base = 2)
c1 = np.transpose(c)
d = np.random.rand(1,7)
d1 = np.transpose(d)
print(a)
print(a.ndim, a1.ndim, a.shape, a1.shape)
print(b)
print(b.ndim, b1.ndim, b.shape, b1.shape)
print(c)
print(c.ndim, c1.ndim, c.shape, c1.shape)
print(d)
print(d.ndim, d1.ndim, d.shape, d1.shape)

[-3 -2 -1  0  1  2  3]
1 1 (7,) (7,)
[0. 1. 2. 3. 4. 5. 6.]
1 1 (7,) (7,)
[  2.   4.   8.  16.  32.  64. 128.]
1 1 (7,) (7,)
[[0.48840477 0.18303718 0.05175021 0.67350513 0.53288225 0.53757706
  0.16956431]]
2 2 (1, 7) (7, 1)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()
Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
- Số chiều và kích thước của ma trận A và ma trận AT
.

In [2]:
import numpy as np
a = np.arange(0, 70, 1)
a.shape = (10,7)
a1 = np.transpose(a)
b = np.linspace(0, 69, 70)
b.shape = (10,7)
b1 = np.transpose(b)
c = np.logspace(0, 10, num=70, base = 2)
c.shape = (10,7)
c1 = np.transpose(c)
d = np.random.rand(1, 70)
d.shape = (10,7)
d1 = np.transpose(d)
print(a)
print(a.ndim, a1.ndim, a.shape, a1.shape)
print(b)
print(b.ndim, b1.ndim, b.shape, b1.shape)
print(c)
print(c.ndim, c1.ndim, c.shape, c1.shape)
print(d)
print(d.ndim, d1.ndim, d.shape, d1.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
2 2 (10, 7) (7, 10)
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68. 69.]]
2 2 (10, 7) (7, 10)
[[1.00000000e+00 1.10567512e+00 1.22251746e+00 1.35170714e+00
  1.49454895e+00 1.65248558e+00 1.82711218e+00]
 [2.02019248e+00 2.23367655e+00 2.46972058e+00 2.73070859e+00
  3.01927653e+00 3.33833893e+00 3.69111829e+00]
 [4.08117764e+00 4.51245656e+00 4.98931093e+00 5.51655694e+00
  6.09951974e+00 6.74408719e+00 7.45676939e+00]
 [8.24476436e+00 9.11603079e+00 1.00793684e+01 1.11445068e+01
  1.23222039e+01

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [3]:
import numpy as np
a = np.arange(0, 70, 1)
a.shape = (10,7)
a1 = a.flatten()
a2 = a1.reshape(10,7)
b = np.linspace(0, 69, 70)
b.shape = (10,7)
b1 = b.flatten()
b2 = b1.reshape(10,7)
c = np.logspace(0, 10, num=70, base = 2)
c.shape = (10,7)
c1 = c.flatten()
c2 = c1.reshape(10,7)
d = np.random.rand(1, 70)
d.shape = (10,7)
d1 = d.flatten()
d2 = d1.reshape(10,7)
print(a)
print(a1)
print(a2)
print(b)
print(b1)
print(b2)
print(c)
print(c1)
print(c2)
print(d)
print(d1)
print(d2)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58. 59. 60. 61. 62.]
 [63. 64. 65. 66. 67. 68.

Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [6]:
import numpy as np
a = np.logspace(0, 149, num=150)
a.shape = (10,15)
a3 = a[3,:]
a5 = a[:,5]
print("Ma trận : \n", a)
print("Dòng thứ 3: ",a3)
print("Dòng thứ 5: ",a5)

Ma trận : 
 [[1.e+000 1.e+001 1.e+002 1.e+003 1.e+004 1.e+005 1.e+006 1.e+007 1.e+008
  1.e+009 1.e+010 1.e+011 1.e+012 1.e+013 1.e+014]
 [1.e+015 1.e+016 1.e+017 1.e+018 1.e+019 1.e+020 1.e+021 1.e+022 1.e+023
  1.e+024 1.e+025 1.e+026 1.e+027 1.e+028 1.e+029]
 [1.e+030 1.e+031 1.e+032 1.e+033 1.e+034 1.e+035 1.e+036 1.e+037 1.e+038
  1.e+039 1.e+040 1.e+041 1.e+042 1.e+043 1.e+044]
 [1.e+045 1.e+046 1.e+047 1.e+048 1.e+049 1.e+050 1.e+051 1.e+052 1.e+053
  1.e+054 1.e+055 1.e+056 1.e+057 1.e+058 1.e+059]
 [1.e+060 1.e+061 1.e+062 1.e+063 1.e+064 1.e+065 1.e+066 1.e+067 1.e+068
  1.e+069 1.e+070 1.e+071 1.e+072 1.e+073 1.e+074]
 [1.e+075 1.e+076 1.e+077 1.e+078 1.e+079 1.e+080 1.e+081 1.e+082 1.e+083
  1.e+084 1.e+085 1.e+086 1.e+087 1.e+088 1.e+089]
 [1.e+090 1.e+091 1.e+092 1.e+093 1.e+094 1.e+095 1.e+096 1.e+097 1.e+098
  1.e+099 1.e+100 1.e+101 1.e+102 1.e+103 1.e+104]
 [1.e+105 1.e+106 1.e+107 1.e+108 1.e+109 1.e+110 1.e+111 1.e+112 1.e+113
  1.e+114 1.e+115 1.e+116 1.e+117 1.e+1