<a href="https://colab.research.google.com/github/RifleB-1311/Baitap-numpy/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.

In [ ]:
numpy.apply_along_axis (1d_func, axis, array, * args, ** kwargs)

1d_func: hàm bắt buộc để thực hiện trên mảng 1D. Nó chỉ có thể được áp dụng trong các lát 1D của mảng đầu vào và dọc theo một trục cụ thể.
trục: trục bắt buộc dọc theo đó chúng tôi muốn mảng đầu vào được cắt
mảng: mảng đầu vào để làm việc
* args: Đối số bổ sung cho 1D_ function
** kwargs: Các đối số bổ sung cho 1D_ Chức năng

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên



In [3]:
import numpy as np
a= np.random.randint(100,size=(15,17))
print("Ma trận ngẫu nhiên: \n", a)



Ma trận ngẫu nhiên: 
 [[69 13 61 61 11 27 30 30  4 44 79  9 34 55 32 54  2]
 [45 25 18 74  0 80 79 47 26 60 53  8 25  4 19 58 74]
 [55 43 53 43 48 57 99 50 39  7 61 98 98 98 76 71  8]
 [ 9 42  2 15 21 11 28 88 96 59 30 79 69 34 36 34 81]
 [71 52 63 53 31 78 79 83 48 91 48 37  7 58 31 41 59]
 [28 33 33 60 28 23 81 71 19 32 79 22 10 19  6 95 70]
 [74 41  3 14 93 28  9 77 26 13 46 34 27 74 91 28 33]
 [93 92 76 28 69 17 31 88 15 68 61  5 99 83  4 42 46]
 [91 53 46 42 99  1 24 75 20 15  6 81 30 86 76 53 19]
 [21 33 47 20 38 23 35 21 19 27 52 44 87 98 25 71 23]
 [94 86 93 65 32 48 16 29 89  1 67 57 41  1  8 95 81]
 [52 47 19  0 16 96 19 10 30 26 54 65 65 62 38 59 81]
 [10  5 78 11 19 51 65 36 42 68 22 77 93 89 74 83 22]
 [27 29 12  2 49 67  0 88  8 73 38 63 73 39 67 53 86]
 [70 65 11 75 28 70 24 19  9 43 15  8 56 87 98  6 68]]


Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [6]:
b = np.apply_along_axis(max, 1, a)
print(b)
    


[79 80 99 96 91 95 93 99 99 98 95 96 93 88 98]


In [ ]:
Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [5]:
c = np.apply_along_axis(max, 0, a)
print(c)

[94 92 93 75 99 96 99 88 96 91 79 98 99 98 98 95 86]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [7]:
import numpy as np
d = np.apply_along_axis(sum, 0, a)
print(d)

[809 659 615 563 582 677 619 812 490 627 711 687 814 887 681 843 753]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [8]:
def tinh_tong2(a): 
    s = 0
    for i in range(0,len(a)): 
        if i % 2 != 0: 
            s += a[i]
    return s
e = np.apply_along_axis(tinh_tong2, 0, a)
print(e)
f = np.apply_along_axis(tinh_tong2, 1, a)
print(f)

[275 301 207 199 221 317 273 413 213 345 367 286 428 339 195 412 461]
[293 356 467 362 493 355 309 423 406 337 382 365 420 414 373]
