<a href="https://colab.research.google.com/github/RifleB-1311/Baitap-numpy/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×5, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [7]:
import numpy as np
A = np.random.randint(10,size=(7,5))
print(A)

[[6 6 7 5 4]
 [7 5 7 4 6]
 [0 8 9 4 4]
 [7 9 0 8 3]
 [3 6 6 0 6]
 [6 8 8 6 6]
 [8 0 8 1 5]]


Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.
Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [8]:
import numpy as np
A = np.zeros((6,7))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ R7×7, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [9]:
import numpy as np
A = np.random.randint(10,size=(7,7))
print(A)

[[5 4 8 3 1 3 3]
 [7 0 3 6 3 2 9]
 [0 1 1 6 8 0 9]
 [2 3 3 5 5 7 9]
 [1 7 8 4 2 0 6]
 [2 0 4 6 6 2 8]
 [7 4 9 6 0 1 2]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0 trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.
Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra màn hình.

In [11]:
import numpy as np
A = np.zeros((6,6),int)
np.fill_diagonal(A,15)
print(A)

[[15  0  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 15  0  0]
 [ 0  0  0  0 15  0]
 [ 0  0  0  0  0 15]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma
trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường
chéo đều bằng 0.
Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8. Gợi ý: sử dụng hàm
numpy.triu(). Kết quả xuất ra màn hình.

In [16]:
import numpy as np
a= np.random.randint(10,size=(8,8))
b=np.triu(a,-1)
print(b)

[[9 5 0 7 8 3 7 2]
 [2 7 7 8 8 0 3 6]
 [0 1 4 8 1 8 0 8]
 [0 0 7 7 4 1 6 1]
 [0 0 0 9 4 9 2 0]
 [0 0 0 0 9 9 2 2]
 [0 0 0 0 0 3 0 4]
 [0 0 0 0 0 0 0 9]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [21]:
import numpy as np
a= np.random.randint(10,size=(8,8))
b=np.tril(a)
print(b)

[[9 0 0 0 0 0 0 0]
 [6 1 0 0 0 0 0 0]
 [3 5 7 0 0 0 0 0]
 [9 2 9 0 0 0 0 0]
 [1 5 3 3 8 0 0 0]
 [3 3 0 4 4 6 0 0]
 [8 9 1 8 7 3 7 0]
 [8 9 7 1 4 6 1 8]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [23]:
import numpy as np
a = np.identity(9)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 – Phép toán trên ma trận:#Hãy sinh ngẫu nhiên 2 ma trận có kích thước 6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.

In [42]:
import numpy as np

a= np.random.randint(5,size=(6,7))    
b= np.random.randint(5,size=(6,7))
print("Ma trận thứ 1:\n",a)
print("Ma trận thứ 2:\n",b)
print("Tổng 2 ma trận:\n",a+b)


Ma trận thứ 1:
 [[4 0 1 2 2 0 1]
 [4 3 4 3 4 1 4]
 [0 2 3 2 1 1 4]
 [0 4 3 0 4 1 3]
 [2 3 4 1 1 1 0]
 [3 3 0 1 4 3 2]]
Ma trận thứ 2:
 [[1 3 0 2 0 1 4]
 [0 3 3 3 0 4 1]
 [3 1 0 2 0 0 4]
 [3 3 3 0 1 0 4]
 [1 0 1 4 2 2 2]
 [2 1 2 3 4 1 4]]
Tổng 2 ma trận:
 [[5 3 1 4 2 1 5]
 [4 6 7 6 4 5 5]
 [3 3 3 4 1 1 8]
 [3 7 6 0 5 1 7]
 [3 3 5 5 3 3 2]
 [5 4 2 4 8 4 6]]


Hãy sinh ngẫu nhiên 1 ma trận có kích thước 5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất ra màn hình.

In [43]:
x= np.random.randint(5,size=(5,8))    
print("Ma trận ngẫu nhiên:\n",x)
n= int(input("Mời nhập 1 số: "))
print("Tích vô hướng 1 số với ma  trận:\n", n*x)

Ma trận ngẫu nhiên:
 [[2 4 1 3 0 3 0 2]
 [2 1 3 4 1 1 4 0]
 [0 1 4 3 1 1 0 3]
 [2 4 4 4 2 2 3 0]
 [1 2 4 3 2 1 1 4]]
Mời nhập 1 số: 2
Tích vô hướng 1 số với ma  trận:
 [[4 8 2 6 0 6 0 4]
 [4 2 6 8 2 2 8 0]
 [0 2 8 6 2 2 0 6]
 [4 8 8 8 4 4 6 0]
 [2 4 8 6 4 2 2 8]]


Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép
chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.

In [44]:
y= np.random.randint(5, size = (3,7))
print("Ma trận được tạo ngẫu nhiên:\n",y)
t=np.transpose(y)
print("Ma trận sau khi được chuyển vị:\n",t)

Ma trận được tạo ngẫu nhiên:
 [[2 1 3 4 0 0 0]
 [1 4 1 0 0 0 2]
 [0 3 4 1 0 1 3]]
Ma trận sau khi được chuyển vị:
 [[2 1 0]
 [1 4 3]
 [3 1 4]
 [4 0 1]
 [0 0 0]
 [0 0 1]
 [0 2 3]]


Phép nhân 2 ma trận: Am×n ∙ Bn×p = Cm×p. Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3,
tiến hành nhân 2 ma trận này để thu được ma trận C5×3. Xuất các ma trận trên ra màn hình.
Gợi ý: sử dụng hàm numpy.dot()

In [41]:
import numpy as np
a= np.random.randint(5,size=(5,7))
b= np.random.randint(5,size=(7,3))
print("Tích 2 ma trận :\n", np.dot(a,b))

Tích 2 ma trận :
 [[46 46 11]
 [53 50 11]
 [28 32  7]
 [36 39 13]
 [37 28  7]]


Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. Gợi ý: sử dụng hàm numpy.linalg.inv()

In [75]:
import numpy as np 
a= np.random.randint(5,size=(5,5))
print("Ma trận lúc đầu: \n",a)
b= np.linalg.inv(a)
print("Ma trận khả nghịch: \n",b)

Ma trận lúc đầu: 
 [[3 2 4 2 1]
 [0 2 2 4 3]
 [4 2 2 0 0]
 [0 0 3 0 2]
 [4 3 0 4 0]]
Ma trận khả nghịch: 
 [[-0.375    -0.5      -0.15625   0.9375    0.6875  ]
 [ 0.25      1.        0.9375   -1.625    -1.125   ]
 [ 0.5       0.       -0.125    -0.25     -0.25    ]
 [ 0.1875   -0.25     -0.546875  0.28125   0.40625 ]
 [-0.75     -0.        0.1875    0.875     0.375   ]]


Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau

- Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1 vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.

- Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên
1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [67]:
import numpy as np
a = np.random.randint(5,size=(1,8))
print(a)
b= np.random.randint(5,size=(8,1))
print(b)

[[3 3 1 2 0 2 3 2]]
[[1]
 [0]
 [2]
 [3]
 [1]
 [2]
 [2]
 [2]]
