<a href="https://colab.research.google.com/github/RifleB-1311/Baitap-numpy/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Xét không gian R3

, một điểm A trong không gian này có tọa độ là (5, 7, 14). Hãy khởi tạo

giá trị của điểm A nêu trên bằng Numpy.

In [ ]:
import numpy as np
a= np.array([5,7,14])
print(a)


[ 5  7 14]


Bài 2: Mở rộng không gian lên R15, điểm A trong không gian này có tọa độ là (1, 2, 3, 4, 5, 6, 7,
8, 9, 10, 11, 12, 13, 14, 15). Hãy khởi tạo điểm A trong không gian 15 chiều này bằng Numpy.

In [11]:
import numpy as np
a= np.arange(1,16,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Bài 3:Hãy viết chương trình sinh ngẫu nhiên một vector trong không gian Rn với n là số nguyên dương
được nhập vào từ bàn phím. Yêu cầu: sử dụng Numpy.

In [15]:
import numpy as np
n=int(input("Mời nhập số nguyên dương: "))
a= np.random.randn(1,n)
print(a)

Mời nhập số nguyên dương: 3
[[ 1.30377253 -0.34942489  0.56393747]]


Bài 4: Hãy viết chương trình tính chiều dài của vector OA , biết công thức tổng quát để tính chiều dài
vector OA trong không gian Rn
là:

In [59]:
import numpy as np
import math
a= [7,-5, 8]
OA= np.array(a)
print("Ma trận:",OA)
s=0
for i in OA:
  s= s+i**2
print(math.sqrt(s))




Ma trận: [ 7 -5  8]
11.74734012447073


Bài 5: Trong không gian Rn, hãy sinh ngẫu nhiên 2 điểm A và B. Xác định vector AB và tính chiều dài của vector này ‖AB ‖. Lưu ý: sử dụng Numpy.

In [65]:
import numpy as np
import math
n= int(input("Mời nhập số nguyên dương: "))
a= np.random.randn(n)
b= np.random.randn(n)
print("Tọa độ vectơ 1: ",a)
print("Tọa độ vectơ 2: ",b)

ab=b-a
print("Tọa độ vectơ AB: ",ab)

s=0
for i in ab:
  s = s+ i**2
print("Chiều dài vectơ AB :",math.sqrt(s))


Mời nhập số nguyên dương: 3
Tọa độ vectơ 1:  [-0.48455301 -0.4504906  -0.60198017]
Tọa độ vectơ 2:  [1.8991575  0.58536799 0.17516554]
Tọa độ vectơ AB:  [2.38371051 1.03585859 0.77714571]
Chiều dài vectơ AB : 2.712754003756087


Bài 6: Tích vô hướng của 2 vector a & b⃗ (dot product hoặc inner product hoặc scalar product) được
tính theo công thức tổng quát là:

a ∙ b⃗ = a1b1 + a2b2 + ⋯ + anbn

Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b⃗ và tính tích vô hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.inner()

In [46]:
import numpy as np
n= int(input("Mời nhập số nguyên dương: "))
a= np.random.randn(n)
b= np.random.randn(n)
print("Tọa độ vectơ 1: ",a)
print("Tọa độ vectơ 2: ",b)
print("Tích vô hướng của vectơ ab: ",np.inner(a,b))

Mời nhập số nguyên dương: 3
Tọa độ vectơ 1:  [-0.69193513 -1.28339053 -0.02208752]
Tọa độ vectơ 2:  [ 0.71072607 -2.22588973 -0.09239058]
Tích vô hướng của vectơ ab:  2.36695013713983


Bài 7: Tích hữu hướng (cross product) của 2 vector a & b⃗ được tính theo công thức tổng quát là:

a × b⃗ = ‖a ‖‖b⃗ ‖ sin(θ)

Trong không gian Rn, hãy sinh ngẫu nhiên 2 vector a & b⃗ và tính tích hữu hướng của 2 vector này.
Lưu ý: sử dụng numpy để tính tích vô hướng và số nguyên dương n được nhập vào từ bàn phím.
Gợi ý: sử dụng hàm numpy.cross()

In [47]:
import numpy as np
n= int(input("Mời nhập số nguyên dương: "))
a= np.random.randn(n)
b= np.random.randn(n)
print("Tọa độ vectơ 1: ",a)
print("Tọa độ vectơ 2: ",b)
print("Tích vô hướng của vectơ ab: ",np.cross(a,b))

Mời nhập số nguyên dương: 3
Tọa độ vectơ 1:  [0.12109656 0.00648336 0.86062948]
Tọa độ vectơ 2:  [ 0.03162228  0.70056497 -0.50624907]
Tích vô hướng của vectơ ab:  [-0.60620906  0.08852009  0.08463099]


Bài 8 - Phép chuyển vị (transpose): trong numpy, một vector a khi thực hiện chuyển vị sẽ được
thực hiện thông qua thao tác a.T
Hãy viết chương trình sinh ngẫu nhiên một vector a trong không gian Rn, số nguyên dương n
được nhập vào từ bàn phím. Xuất ra màn hình giá của vector a và chuyển vị của vector a

In [48]:
import numpy as np
n= int(input("Mời nhập số nguyên dương: "))
a= np.random.randn(n)
print("Tọa độ vectơ: ",a)
A= np.transpose(a)
print("Ma trận chuyển vị là:", A)

Mời nhập số nguyên dương: 3
Tọa độ vectơ:  [ 0.13338083 -2.58483599  0.51582464]
Ma trận chuyển vị là: [ 0.13338083 -2.58483599  0.51582464]


Bài 9:

In [67]:
import numpy as np
a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]
print(a)    #Xuất a và b ra màn hình
print(b)

a=np.array(a)     #Tạo vector tương ứng từ a và b, xuất kết quả ra màn hình
b=np.array(b)
print(a)    
print(b)

a= np.transpose(a)    #Thực hiện phép chuyển vị đối với 2 vector ở trên và xuất kết quả ra màn hình.
b= np.transpose(b)
print(a)    
print(b)





[1, 2, 3, 4, 5]
[[1], [2], [3], [4], [5]]
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
[[1 2 3 4 5]]


Bài 10: Trong không gian Rn, hãy sinh ngẫu nhiên vector a và b⃗ , n là số nguyên dương nhập vào từ bàn phím. Hãy:

 Thực hiện phép nhân: ma với m là số bất kỳ, xuất kết quả ra màn hình

 Thực hiện phép cộng 2 vector: a + b⃗ và xuất kết quả ra màn hình.

In [81]:
import numpy as np
n= int(input("Mời nhập số nguyên dương: "))
a= np.random.randn(n)
b= np.random.randn(n)
print("Tọa độ vectơ 1: ",a)
print("Tọa độ vectơ 2: ",b)

m=random.randint(1,10)
print("Số ngẫu nhiên: ",m)

tich= m*a
tong= a+b
print("Phép nhân ma: ",tich)
print("Tổng 2 vecto: ",tong)

Mời nhập số nguyên dương: 3
Tọa độ vectơ 1:  [-0.19225792 -1.12774303  0.55875872]
Tọa độ vectơ 2:  [ 1.50135711  1.61902722 -0.6197172 ]
Số ngẫu nhiên:  9
Phép nhân ma:  [ -1.73032126 -10.14968731   5.02882849]
Tổng 2 vecto:  [ 1.3090992   0.49128418 -0.06095848]
