<a href="https://colab.research.google.com/github/RifleB-1311/Baitap-numpy/blob/main/Pandas01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Khởi tạo 1 Series với giá trị rỗng

In [1]:
import numpy as np
a = np.empty((3))
a[:] = None
print(a)


[nan nan nan]


Câu 2: Giả sử có 1 vector hàng a có kích thước (1x7) được biểu diễn trong NumPy, hãy tạo 1
series tương ứng với các giá trị được sinh ngẫu nhiên.

In [ ]:
import numpy as np
import pandas
import random
lst=[]
for i in range(7):
  var = random.randrange(10)
  lst.append(var)
a = np.array(lst)
print(a)
myvar = pd.Series(a, index = ["a[0]", "a[1]", "a[2]","a[3]","a[4]","a[5]","a[6]"])
print(myvar)

[2 4 5 9 4 1 2]
a[0]    2
a[1]    4
a[2]    5
a[3]    9
a[4]    4
a[5]    1
a[6]    2
dtype: int64


Câu 3: Giả sử có 1 vector hàng a có kích thước (1x7), hãy nhập các giá trị cho 7 phần tử này từ
bàn phím và tạo series tương ứng.

In [ ]:
import numpy as np
import pandas as pd
lst=[]
for i in range(7):
  var= int(input("Mời nhập giá trị: "))
  lst.append(var)
a = np.array(lst)
print(a)
myvar = pd.Series(a, index = ["a[0]", "a[1]", "a[2]","a[3]","a[4]","a[5]","a[6]"])
print(myvar)

Mời nhập giá trị: 1
Mời nhập giá trị: 2
Mời nhập giá trị: 3
Mời nhập giá trị: 4
Mời nhập giá trị: 5
Mời nhập giá trị: 6
Mời nhập giá trị: 7
[1 2 3 4 5 6 7]
a[0]    1
a[1]    2
a[2]    3
a[3]    4
a[4]    5
a[5]    6
a[6]    7
dtype: int64


Câu 4: Giả sử có 1 vector cột có kích thước (7x1) được biểu diễn trong NumPy, hãy tạo Series
tương ứng.

In [ ]:
import numpy as np
import pandas as pd
#lst=[1,2,3,4,5,6,7]
#a= np.array(lst)
#print(a)
a= np.random.randint(10,size=(7,1))
print(a)
b=[]
for i in a:
  b.append(i)
print(b)

[[7]
 [9]
 [3]
 [3]
 [0]
 [1]
 [1]]
[array([7]), array([9]), array([3]), array([3]), array([0]), array([1]), array([1])]


Câu 5: Chuyển đổi dữ liệu, hãy thực hiện các yêu cầu sau:
- Chuyển 1 list thành 1 series
- Chuyển 1 tuple thành 1 series
- Chuyển 1 dictionary thành 1 series


In [3]:
import pandas as pd
a = [1,2,3,4,5]
b = list((1,2,3,4,5))
c = {1: 9, 2: 8, 3: 7}
d = pd.Series(a)
e = pd.Series(b)
f = pd.Series(c)
print(d)
print(e)
print(f)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
1    9
2    8
3    7
dtype: int64


Câu 6: Mỗi phần tử của series đều gắn liền với các chỉ số (index) tương ứng, hãy tạo một series
có kích thước (1x20) với giá trị ngẫu nhiên:
- Xuất series ra màn hình
- Xuất các chỉ số của series ra màn hình
- Thay đổi cách đánh chỉ số mặc định của series từ đánh chỉ số bằng số nguyên sang các kiểu
đánh chỉ số bằng label và in kết quả ra màn hình
Gợi ý:
- Hàm loc() dùng cho chỉ số label
- Hàm iloc() dùng cho chỉ số đạng số nguyên
- Hàm ix(): dùng cho cả 2 loại chỉ số trên

In [4]:
import random
import pandas as pd
a = []
for i in range(0,20):
    b = random.randint(0,40)
    a.append(b)
n = pd.Series(a)
print(n)
for i in range(0,20):
    print(a[i])
c = pd.Series(a, index = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t"])
print(c)

0      0
1     18
2      0
3     12
4     17
5     23
6     36
7     33
8     15
9     38
10    39
11     2
12    16
13    20
14    14
15    37
16    10
17    40
18    20
19    19
dtype: int64
0
18
0
12
17
23
36
33
15
38
39
2
16
20
14
37
10
40
20
19
a     0
b    18
c     0
d    12
e    17
f    23
g    36
h    33
i    15
j    38
k    39
l     2
m    16
n    20
o    14
p    37
q    10
r    40
s    20
t    19
dtype: int64
